# -*- coding: utf-8 -*-
"""Zomato_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VGkfgYoPcl4zQPRt8GZ_cMNeheDki2Hi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv('/content/Zomato data .csv')
print(dataset)

"""**Converting the data type of the column rate**"""

def handleRate(value):
  value=str(value).split('/')
  value=value[0];
  return float(value)
dataset['rate']=dataset['rate'].apply(handleRate)
print(dataset.head())

"""**Types of resturants**

Q1) What type of retaurants do the majority of customers order from?

---


Answer: **Dining**
"""

sns.countplot(x=dataset['listed_in(type)'])
plt.xlabel('type of resturants')

"""Q2) How many votes has each type of restaurant recieved from customers?

---


Answer:
Dining:20000,
Cafes:around 6000,
Buffet:around 3000,
Other: around 8000

"""

grouped_data=dataset.groupby('listed_in(type)')['votes'].sum()
results=pd.DataFrame({'votes':grouped_data})
plt.plot(results,c='Green',marker='o')
plt.xlabel('Types of restaurant',c='red',size=20)
plt.ylabel('votes',c='red',size=20)

"""Q3) What are the ratings that the majority of restaurants have received?

---


Answer: Majority of the ratings are between 3.5 to 4.
"""

plt.hist(dataset['rate'],bins=5)
plt.title('Rate Distribution')
plt.show()

"""Q4) Zomato has observed that most couples order most of their food online.What is their average spending on each order?

---


Answer: Rs 300
"""

couple_data=dataset['approx_cost(for two people)']
sns.countplot(x=couple_data)

"""Q5)Which mode(online or offline) has received the maximum rating?

---


Answer:Online Mode received maximum rating.
"""

plt.plot(figsize=(6,6))
sns.boxplot(x='online_order',y='rate',data=dataset)

"""Q6)Which type of restaurant received more offline orders,so that Zomato can provide customers with good offers?

---


Answer:Dining
"""

pivot_table=dataset.pivot_table(index='listed_in(type)',columns='online_order',aggfunc='size',fill_value=0)
sns.heatmap(pivot_table,annot=True,cmap='YlGnBu',fmt='d')
plt.title('Heatmap')
plt.xlabel('Online Order')
plt.ylabel('Listed Types')
plt.show()

"""**Conclusion**

---
Dining restaurants primarily receive offline orders whereas cafes primarily receive online orders.This suggests that clients prefer ordering in person at
restaurants but perfer ordering online at cafes.
"""